services:
  elasticsearch7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      ELASTIC_PASSWORD: changeme
      xpack.security.enabled: "false"
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
    healthcheck:
      test: curl -f http://elastic:changeme@elasticsearch:8200
      interval: 10s
      timeout: 1s
    networks:
      - public
    volumes:
      - esdata:/usr/share/elasticsearch/data
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: rorapi
      MYSQL_ROOT_PASSWORD: dummypassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - public
  web:
    container_name: rorapiweb
    env_file: .env
    environment:
      - ELASTIC_HOST=elasticsearch7
      - ELASTIC_PORT=9200
      - ELASTIC_PASSWORD=changeme
      - ROR_BASE_URL=http://localhost
      - DATA_STORE=data.dev.ror.org
      - DB_PASSWORD=dummypassword
    build: .
    develop:
      watch:
          - action: sync+exec
            path: ./rorapi
            target: /home/app/webapp/rorapi
            initial_sync: true
            exec:
              command: passenger-config restart-app .
    #image: rorcommunity/ror-api
    ports:
      - "9292:80"
      - "2222:22"
    networks:
      - public
    depends_on:
      - elasticsearch7
      - db
volumes:
  mysql_data:
    driver: local
  esdata:
    driver: local

networks:
  public:
    driver: bridge
