# Generated by Django 2.2.28 on 2025-04-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapi', '0002_auto_20250326_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='institution_ror',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ror_use',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
