name: Test Pull Request
on:
  pull_request:
    branches:
      - 'dev'
      - 'staging'
      - 'master'
  workflow_dispatch:
jobs:
  test-pr:
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit
